package com.ems.leave_service.api.operations.find.leave.leaves_by_employee_id_and_date_range;

import com.ems.leave_service.api.base.OperationProcessor;

public interface FindLeavesByEmployeeIdAndDateRangeOperation extends OperationProcessor<FindLeavesByEmployeeIdAndDateRangeResponse, FindLeavesByEmployeeIdAndDateRangeRequest> {
}
