package com.ems.employee_service.api.operations.find.bysalary.anddesignation;

import com.ems.employee_service.api.base.OperationProcessor;

public interface FindEmployeesByDesignationOrderBySalaryOperation extends OperationProcessor<FindEmployeesByDesignationOrderBySalaryResponse, FindEmployeesByDesignationOrderBySalaryRequest> {
}
